# Generated by Django 3.1.7 on 2021-03-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.CharField(max_length=50, unique=True, verbose_name='recording')),
                ('recording_tag', models.CharField(max_length=50, verbose_name='recording tag')),
                ('recorded_call_id', models.IntegerField(unique=True, verbose_name='recorded call id')),
                ('recorder_cid', models.IntegerField(blank=True, null=True, verbose_name='recorder cid')),
                ('recorded_cid', models.CharField(blank=True, max_length=50, null=True, verbose_name='recorded cid')),
                ('recorder_account_id', models.IntegerField(blank=True, null=True, verbose_name='recorder account id')),
                ('recorded_account_id', models.IntegerField(blank=True, null=True, verbose_name='recorded account id')),
                ('from_account_id', models.IntegerField(blank=True, null=True, verbose_name='Account ID (from)')),
                ('from_caller_id', models.CharField(max_length=50, verbose_name='Caller ID (from)')),
                ('to_account_id', models.IntegerField(blank=True, null=True, verbose_name='Account ID (to)')),
                ('to_caller_id', models.CharField(max_length=50, verbose_name='Caller ID (to)')),
                ('duration', models.IntegerField(verbose_name='duration (in seconds)')),
                ('date_created_ts', models.DateTimeField(verbose_name='date created')),
                ('date_created_secs', models.CharField(max_length=50, verbose_name='date created (in seconds)')),
            ],
            options={
                'verbose_name': 'Recordings',
                'verbose_name_plural': 'Recordings',
                'db_table': 'recordings',
                'managed': True,
            },
        ),
    ]
