# Generated by Django 3.1.7 on 2021-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='recording',
            field=models.URLField(max_length=500, unique=True, verbose_name='recording'),
        ),
    ]
