# Generated by Django 3.1.7 on 2021-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20210310_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='date_created_secs',
            field=models.TimeField(verbose_name='date created (in seconds)'),
        ),
    ]
