# Generated by Django 3.1.7 on 2021-03-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_auto_20210310_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordings',
            name='date_created_secs',
        ),
    ]
