# Generated by Django 3.1.7 on 2021-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_remove_recordings_date_created_secs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='recorder_cid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='recorded cid'),
        ),
    ]
